-- TrackFlow Schema
-- Scalable schema for event tracking and user sessions.
--
-- The events table is range-partitioned by created_at so recent queries can
-- prune unrelated time ranges and retention can operate on bounded partitions.

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    plan VARCHAR(20) DEFAULT 'free',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE sessions (
    id BIGSERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ,
    duration_seconds INTEGER
);

-- A partial index keeps the active-session monitor focused on the small,
-- mutable subset instead of scanning every historical session.
CREATE INDEX idx_sessions_active
    ON sessions (started_at DESC)
    WHERE ended_at IS NULL;
CREATE INDEX idx_sessions_user_started
    ON sessions (user_id, started_at DESC);

-- A partitioned table's primary key must include the partition key. The
-- composite key also makes an archive copy unambiguous.
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    session_id BIGINT REFERENCES sessions(id),
    event_type VARCHAR(50) NOT NULL,
    properties JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Create a three-year operating window of monthly partitions. The default
-- partition safely accepts dates outside this window until the partition
-- maintenance job creates the next month. In production, pre-create future
-- partitions and validate that the default partition remains empty.
DO $$
DECLARE
    partition_start DATE := DATE '2025-01-01';
    partition_end DATE;
    partition_name TEXT;
BEGIN
    WHILE partition_start < DATE '2028-01-01' LOOP
        partition_end := (partition_start + INTERVAL '1 month')::DATE;
        partition_name := format('events_%s', to_char(partition_start, 'YYYY_MM'));
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF events FOR VALUES FROM (%L) TO (%L)',
            partition_name,
            partition_start,
            partition_end
        );
        partition_start := partition_end;
    END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS events_default PARTITION OF events DEFAULT;

-- PostgreSQL propagates these indexes to every existing and future partition.
-- The first index supports the user activity feed; the second supports the
-- recent-window metrics predicate and event-type grouping.
CREATE INDEX idx_events_user_created_at
    ON events (user_id, created_at DESC);
CREATE INDEX idx_events_created_type
    ON events (created_at, event_type);

-- Cold data is intentionally kept outside the hot, partitioned event table.
-- The archive has the same logical key so rows can be validated during a
-- migration and can be restored without changing event identifiers.
CREATE TABLE events_archive (
    id BIGINT NOT NULL,
    user_id INTEGER NOT NULL,
    session_id BIGINT,
    event_type VARCHAR(50) NOT NULL,
    properties JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL,
    archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, created_at)
);

CREATE INDEX idx_events_archive_user_created_at
    ON events_archive (user_id, created_at DESC);
CREATE INDEX idx_events_archive_created_at
    ON events_archive (created_at);

-- Move data older than the supplied cutoff into the archive in one
-- transaction. In a production deployment, invoke this in small time-bounded
-- batches or detach and copy complete old partitions to reduce lock duration.
CREATE OR REPLACE FUNCTION archive_events_before(p_cutoff TIMESTAMPTZ)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    moved_rows BIGINT;
BEGIN
    IF p_cutoff IS NULL THEN
        RAISE EXCEPTION 'archive cutoff must not be null';
    END IF;

    WITH moved AS (
        DELETE FROM events
        WHERE created_at < p_cutoff
        RETURNING id, user_id, session_id, event_type, properties, created_at
    )
    INSERT INTO events_archive (
        id, user_id, session_id, event_type, properties, created_at
    )
    SELECT id, user_id, session_id, event_type, properties, created_at
    FROM moved;

    GET DIAGNOSTICS moved_rows = ROW_COUNT;
    RETURN moved_rows;
END;
$$;

CREATE TABLE feature_usage (
    id BIGSERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    feature_name VARCHAR(100) NOT NULL,
    used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    count INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX idx_feature_usage_user_used_at
    ON feature_usage (user_id, used_at DESC);
CREATE INDEX idx_feature_usage_feature_used_at
    ON feature_usage (feature_name, used_at DESC);
